apiVersion: apps/v1
kind: Deployment
metadata:
  name: cckubernetesproduct-seq
spec:
  selector:
    matchLabels:
      app: seq-app
  replicas: 1
  template:
    metadata:
      labels:
        app: seq-app
    spec:      
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 5341
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
        - name: ACCEPT_EULA
          value: "Y"        
---
apiVersion: v1
kind: Service
metadata:
  name: cckubernetesproduct-seq-ui-service
spec:
  selector:
    app: seq-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: cckubernetesproduct-seq-log-service
spec:
  selector:
    app: seq-app
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341
      nodePort: 30300
  type: NodePort