kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cckubernetes-mssql-persistent-volume
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cckubernetes-mssql-persistent-volume-claim
  annotations: 
    volume.beta.kubernetes.io/storage-class: cckubernetes-mssql-persistent-volume
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi