apiVersion: apps/v1
kind: Deployment
metadata:
  name: cckubernetesproduct-mssql
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cckubernetesproduct-secret
              key: db-password-secret
        volumeMounts:
        - name: cckubernetes-mssql-persistent-storage
          mountPath: /mysql
      volumes:
      - name: cckubernetes-mssql-persistent-storage
        persistentVolumeClaim:
          claimName: cckubernetes-mssql-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cckubernetesproduct-mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30200
  type: NodePort