apiVersion: v1
kind: Secret
metadata:
  name:  cckubernetesproduct-secret
data:
   db-connection-string-secret: U2VydmVyPWNja3ViZXJuZXRlc3Byb2R1Y3QtbXNzcWwtc2VydmljZTtEYXRhYmFzZT1DQ0t1YmVybmV0ZXNQcm9kdWN0cztVc2VyPVNBO1Bhc3N3b3JkPTEyMzQ1Njc4QWE7SW50ZWdyYXRlZCBTZWN1cml0eT1mYWxzZTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZTs=
   db-password-secret: MTIzNDU2NzhBYQ==
type: Opaque